# Generated by Django 2.2 on 2020-06-10 12:45

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moogts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Argument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('argument', models.CharField(max_length=500)),
                ('type', models.CharField(choices=[('NORMAL', 'Normal Argument'), ('CONCLUDING', 'Concluding Argument')], default='NORMAL', max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('moogt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arguments', to='moogts.Moogt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arguments', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ArgumentStats',
            fields=[
                ('argument', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='arguments.Argument')),
                ('applauds', models.ManyToManyField(related_name='_argumentstats_applauds_+', to=settings.AUTH_USER_MODEL)),
                ('downvotes', models.ManyToManyField(related_name='_argumentstats_downvotes_+', to=settings.AUTH_USER_MODEL)),
                ('upvotes', models.ManyToManyField(related_name='_argumentstats_upvotes_+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
