# Generated by Django 2.2 on 2020-08-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
