# Generated by Django 2.2 on 2020-11-24 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0002_argument_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='reply_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arguments.Argument'),
        ),
    ]
