# Generated by Django 2.2 on 2020-11-25 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arguments', '0003_argument_reply_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='argument',
            name='modified_child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_parent', to='arguments.Argument'),
        ),
        migrations.CreateModel(
            name='ArgumentActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Accepted', 'ACCEPTED'), ('Declined', 'DECLINED')], default='Pending', max_length=15)),
                ('type', models.CharField(choices=[('Edit', 'EDIT'), ('Delete', 'DELETE')], default='Edit', max_length=15)),
                ('argument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='arguments.Argument')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
