# Generated by Django 2.2 on 2020-11-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0004_auto_20201125_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='argument',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal Argument'), ('CONCLUDING', 'Concluding Argument'), ('DELETED', 'Deleted Argument')], default='NORMAL', max_length=50),
        ),
    ]
