# Generated by Django 2.2 on 2020-12-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0005_auto_20201126_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal Argument'), ('CONCLUDING', 'Concluding Argument'), ('DELETED', 'Deleted Argument'), ('WAIVED', 'Waived Argument')], default='NORMAL', max_length=50),
        ),
    ]
