# Generated by Django 2.2 on 2020-12-04 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0006_auto_20201202_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='argument',
            name='react_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='arguments.Argument'),
        ),
        migrations.AddField(
            model_name='argument',
            name='reaction_type',
            field=models.CharField(choices=[('ENDORSEMENT', 'Endorsement'), ('DISAGREEMENT', 'Disagreement')], default='ENDORSEMENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='argument',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal Argument'), ('CONCLUDING', 'Concluding Argument'), ('DELETED', 'Deleted Argument'), ('WAIVED', 'Waived Argument'), ('REACTION', 'Reaction Argument')], default='NORMAL', max_length=50),
        ),
    ]
