# Generated by Django 2.2 on 2020-12-07 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0008_auto_20201205_0806'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArgumentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='argument_images')),
                ('argument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='arguments.Argument')),
            ],
        ),
    ]
