# Generated by Django 2.2 on 2020-12-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0009_argumentimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal Argument'), ('CONCLUDING', 'Concluding Argument'), ('DELETED', 'Deleted Argument'), ('WAIVED', 'Waived Argument'), ('REACTION', 'Reaction Argument'), ('MISSED_TURN', 'Missed Turn')], default='NORMAL', max_length=50),
        ),
    ]
