# Generated by Django 2.2 on 2020-12-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0010_auto_20201209_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='reaction_type',
            field=models.CharField(choices=[('ENDORSEMENT', 'Endorsement'), ('DISAGREEMENT', 'Disagreement')], default=None, max_length=50, null=True),
        ),
    ]
