# Generated by Django 2.2 on 2021-01-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0013_argument_consecutive_expired_turns_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal Argument'), ('CONCLUDING', 'Concluding Argument'), ('DELETED', 'Deleted Argument'), ('WAIVED', 'Waived Argument'), ('REACTION', 'Reaction Argument'), ('MISSED_TURN', 'Missed Turn'), ('MOOGT_STARTED', 'Moogt Started'), ('MOOGT_PAUSED', 'Moogt Paused'), ('MOOGT_RESUMED', 'Moogt Resumed'), ('MOOGT_BROKE_OFF', 'Moogt Broke Off'), ('MOOGT_ENDED', 'Moogt Ended'), ('MOOGT_OVER', 'Moogt Over'), ('REACTION_WITHOUT_STATEMENT', 'Argument Reacted Without Statement')], default='NORMAL', max_length=50),
        ),
    ]
