# Generated by Django 2.2 on 2021-02-08 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0014_auto_20210130_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='react_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moogter_reactions', to='arguments.Argument'),
        ),
    ]
