# Generated by Django 2.2 on 2021-02-25 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0015_auto_20210208_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentstats',
            name='disagreement_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='argumentstats',
            name='endorsement_count',
            field=models.IntegerField(default=0),
        ),
    ]
