# Generated by Django 2.2 on 2021-02-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0015_auto_20210216_1206'),
        ('arguments', '0016_auto_20210225_1259'),
    ]

    operations = [
    ]
