# Generated by Django 2.2 on 2021-03-30 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0020_auto_20210323_0824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argumentactivity',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Accepted', 'ACCEPTED'), ('Declined', 'DECLINED'), ('Cancelled', 'CANCELLED'), ('Expired', 'EXPIRED')], default='Pending', max_length=15),
        ),
    ]
