# Generated by Django 2.2 on 2021-04-20 14:13

from django.db import migrations

from meda.enums import ArgumentType


def remove_reaction_without_statement_arguments(apps, schema_editor):
    Argument = apps.get_model('arguments', 'Argument')
    Argument.objects.filter(type=ArgumentType.REACTION_WITHOUT_STATEMENT.name).delete()


def reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('arguments', '0021_auto_20210330_1210'),
    ]

    operations = [
        migrations.RunPython(remove_reaction_without_statement_arguments, reverse),
    ]
