# Generated by Django 2.2 on 2022-01-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0022_auto_20210420_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='argument',
            name='type',
            field=models.CharField(choices=[('NORMAL', 'Normal Argument'), ('MODERATOR_ARGUMENT', 'Moderator Argument'), ('CONCLUDING', 'Concluding Argument'), ('DELETED', 'Deleted Argument'), ('WAIVED', 'Waived Argument'), ('REACTION', 'Reaction Argument'), ('MISSED_TURN', 'Missed Turn'), ('MOOGT_STARTED', 'Moogt Started'), ('MOOGT_PAUSED', 'Moogt Paused'), ('AUTO_PAUSED', 'Moogt automatically paused.'), ('MOOGT_RESUMED', 'Moogt Resumed'), ('MOOGT_BROKE_OFF', 'Moogt Broke Off'), ('MOOGT_ENDED', 'Moogt Ended'), ('MOOGT_OVER', 'Moogt Over'), ('REACTION_WITHOUT_STATEMENT', 'Argument Reacted Without Statement')], default='NORMAL', max_length=50),
        ),
    ]
