# Generated by Django 2.2 on 2022-03-17 09:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('arguments', '0025_auto_20220314_0712'),
    ]

    operations = [
        migrations.AddField(
            model_name='argumentreport',
            name='action_taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='argumentreport',
            name='remark',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='argumentreport',
            name='status',
            field=models.CharField(choices=[('PEN', 'Pending'), ('DEL', 'Item Deleted'), ('WAR', 'User Warned'), ('DEC', 'Account Deactivated')], default='PEN', max_length=3),
        ),
        migrations.AlterField(
            model_name='argumentactivity',
            name='status',
            field=models.CharField(choices=[('Pending', 'PENDING'), ('Accepted', 'ACCEPTED'), ('Declined', 'DECLINED'), ('Cancelled', 'CANCELLED'), ('Expired', 'EXPIRED'), ('Waiting', 'WAITING')], default='Pending', max_length=15),
        ),
    ]
