# Generated by Django 2.1.3 on 2019-04-07 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20190329_0224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='href',
        ),
        migrations.AddField(
            model_name='activity',
            name='object_id',
            field=models.IntegerField(default=None),
        ),
    ]
