# Generated by Django 2.1.3 on 2019-04-07 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190407_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='object_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
