# Generated by Django 2.1.3 on 2019-11-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190525_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('create_moogt', 'Create Moogt'), ('create_argument', 'Create Argument'), ('follow_user', 'Follow User')], max_length=25),
        ),
    ]
