# Generated by Django 2.1.3 on 2019-12-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191124_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('create_moogt', 'Create Moogt'), ('create_argument', 'Create Argument'), ('follow_user', 'Follow User'), ('upvote_argument', 'Upvote Argument'), ('downvote_argument', 'Downvote Argument'), ('make_comment', 'Comment Argument')], max_length=25),
        ),
    ]
