# Generated by Django 2.1.3 on 2019-12-06 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191124_0053'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('create_moogt', 'Create Moogt'), ('create_argument', 'Create Argument'), ('follow_user', 'Follow User'), ('view_moogt', 'View Moogt'), ('make_comment', 'Make Comment'), ('like_moogt', 'Like Moogt')], max_length=25),
        ),
        migrations.AddField(
            model_name='creditpoint',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='users.Activity'),
        ),
    ]
