# Generated by Django 2.1.3 on 2019-12-09 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191206_0119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditpoint',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_points', to='users.Activity'),
        ),
    ]
