# Generated by Django 2.1.3 on 2019-12-10 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191209_0629'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpoint',
            name='type',
            field=models.CharField(choices=[('create_moogt', 'Create Moogt'), ('create_argument', 'Create Argument'), ('follow_user', 'Follow User'), ('view_moogt', 'View Moogt'), ('make_comment', 'Make Comment'), ('upvote_moogt', 'Upvote Moogt'), ('downvote_moogt', 'Downvote Moogt')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('create_moogt', 'Create Moogt'), ('create_argument', 'Create Argument'), ('follow_user', 'Follow User'), ('view_moogt', 'View Moogt'), ('make_comment', 'Make Comment'), ('upvote_moogt', 'Upvote Moogt'), ('downvote_moogt', 'Downvote Moogt')], max_length=25),
        ),
        migrations.AlterField(
            model_name='creditpoint',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_points', to='users.Activity'),
        ),
    ]
