# Generated by Django 2.1.3 on 2019-12-12 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20191210_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpoint',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credit_points', to='users.Profile'),
        ),
    ]
