# Generated by Django 2.1.3 on 2019-12-14 18:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20191214_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditpoint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
