# Generated by Django 2.1.3 on 2020-01-03 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191221_0704'),
        ('users', '0016_creditpoint_created_at'),
    ]

    operations = [
    ]
