# Generated by Django 2.2 on 2020-09-22 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20200914_0808'),
        ('users', '0020_auto_20200830_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogtmedauser',
            name='priority_conversations',
            field=models.ManyToManyField(related_name='prioritizers', to='chat.Conversation'),
        ),
    ]
