# Generated by Django 2.2 on 2020-12-11 08:07

from django.db import migrations


# This is for create a wallet for users who don't have one yet.
def create_wallet(apps, schema_editor):
    User = apps.get_model('users', 'MoogtMedaUser')
    Wallet = apps.get_model('users', 'Wallet')

    for user in User.objects.all():
        Wallet.objects.create(user=user)


def reverse_create_wallet(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0023_wallet'),
    ]

    operations = [
        migrations.RunPython(create_wallet, reverse_create_wallet)
    ]
