# Generated by Django 2.2 on 2020-12-27 16:43

import annoying.fields
from django.conf import settings
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20201211_0807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='user',
            field=annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='wallet', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
