# Generated by Django 2.2 on 2021-06-09 07:34

from django.db import migrations, models


# This is for changing the default wallet credit.
def update_wallet(apps, schema_editor):
    Wallet = apps.get_model('users', 'Wallet')

    Wallet.objects.all().update(credit=5_000)


def reverse_update_wallet(apps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('users', '0025_auto_20201227_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='credit',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
        migrations.RunPython(update_wallet, reverse_update_wallet)
    ]
