# Generated by Django 2.2 on 2022-01-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20220114_1145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moogtmedauser',
            name='blocker',
        ),
        migrations.RemoveField(
            model_name='moogtmedauser',
            name='blocking',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_pic',
        ),
        migrations.AddField(
            model_name='profile',
            name='cover_photo',
            field=models.ImageField(blank=True, upload_to='cover_photos'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_photo',
            field=models.ImageField(blank=True, upload_to='profile_photos'),
        ),
    ]
