# Generated by Django 2.2 on 2022-02-03 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20220124_0911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blocking',
            options={'ordering': ['-created_at']},
        ),
    ]
