# Generated by Django 2.2 on 2022-02-15 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_auto_20220203_1604'),
        ('users', '0031_auto_20220210_0917'),
    ]

    operations = [
    ]
