# Generated by Django 2.2 on 2023-01-22 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0037_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='firebase_uid',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.TextField(unique=True),
        ),
    ]
