# Generated by Django 2.2 on 2023-01-22 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_auto_20230122_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='firebase_uid',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_number',
            field=models.CharField(error_messages={'unique': 'A user with that phone number already exists.'}, max_length=15, unique=True),
        ),
    ]
