# Generated by Django 4.2.5 on 2023-09-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0039_auto_20230122_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='firebase_uid',
            field=models.CharField(error_messages={'unique': 'A user already exists.'}, max_length=50, unique=True),
        ),
    ]
