# [START django_app]
runtime: python
env: flex
entrypoint: gunicorn --bind 0.0.0.0:8080 moogtmeda.wsgi -w 4

runtime_config:
    python_version: 3

# This sample incurs costs to run on the App Engine flexible environment.
# The settings below are to reduce costs during testing and are not appropriate
# for production use. For more information, see:
# https://cloud.google.com/appengine/docs/flexible/python/configuring-your-app-with-app-yaml
manual_scaling:
    instances: 1
resources:
    cpu: 2
    memory_gb: 2.3
    disk_size_gb: 10

#handlers:
#  # This configures Google App Engine to serve the files in the app's static
#  # directory.
#  - url: /static
#    static_dir: static/
#
#  # This handler routes all requests not caught above to your main app. It is
#  # required when static routes are defined, but can be omitted (along with
#  # the entire handlers section) when there are no static files defined.
#  - url: /.*
#    script: auto

handlers:
    - url: /.*
      script: auto
      secure: always
      redirect_http_response_code: 301

beta_settings:
    cloud_sql_instances: moogter-backend-dev:europe-west6:moogter-dev-db

vpc_access_connector:
    name: "projects/moogter-backend-dev/locations/europe-west6/connectors/moogter-dev-connector"
# [END django_app]
