# Generated by Django 2.2 on 2020-09-03 07:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0004_moogtminisuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0003_regularmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniSuggestionMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_suggestion_messages', to='chat.Conversation')),
                ('mini_suggestion', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='message', to='moogts.MoogtMiniSuggestion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
