# Generated by Django 2.2 on 2020-09-14 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_conversation_last_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationmessage',
            name='content',
            field=models.CharField(max_length=560, null=True),
        ),
        migrations.AddField(
            model_name='minisuggestionmessage',
            name='content',
            field=models.CharField(max_length=560, null=True),
        ),
    ]
