# Generated by Django 2.2 on 2020-09-25 07:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_auto_20200914_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitationmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='_invitationmessage_read_by_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='minisuggestionmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='_minisuggestionmessage_read_by_+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='regularmessage',
            name='read_by',
            field=models.ManyToManyField(related_name='_regularmessage_read_by_+', to=settings.AUTH_USER_MODEL),
        ),
    ]
