# Generated by Django 2.2 on 2020-10-03 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0007_auto_20200925_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('verb', models.CharField(max_length=255)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('invitation_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='chat.InvitationMessage')),
                ('mini_suggestion_message', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='summaries', to='chat.MiniSuggestionMessage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
