# Generated by Django 2.2 on 2020-10-20 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_auto_20201019_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitationmessage',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='minisuggestionmessage',
            name='read_by',
        ),
        migrations.RemoveField(
            model_name='regularmessage',
            name='read_by',
        ),
        migrations.AddField(
            model_name='invitationmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='minisuggestionmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='regularmessage',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
