# Generated by Django 2.2 on 2020-10-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_regularmessage_forwarded_from'),
        ('chat', '0010_auto_20201022_0746'),
    ]

    operations = [
    ]
