# Generated by Django 2.2 on 2021-12-15 06:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invitations', '0007_auto_20211214_1604'),
        ('chat', '0014_auto_20201203_0701'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeratorInvitationMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('is_removed', models.BooleanField(default=False)),
                ('content', models.CharField(max_length=560, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_invitation_messages', to='chat.Conversation')),
                ('moderator_invitation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderator_message', to='invitations.ModeratorInvitation')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
