# Generated by Django 2.2 on 2022-01-28 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0016_messagesummary_moderator_invitation_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
    ]
