# Generated by Django 2.2 on 2022-02-21 08:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0017_conversation_is_locked'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invitationmessage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='minisuggestionmessage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='moderatorinvitationmessage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='regularmessage',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
