# Generated by Django 2.2 on 2022-03-09 07:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0018_auto_20220221_0855'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='invitationmessage',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='moderatorinvitationmessage',
            managers=[
            ],
        ),
    ]
