# Generated by Django 2.2 on 2022-03-31 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0019_auto_20220309_0747'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='regularmessage',
            managers=[
            ],
        ),
    ]
