from django.urls import re_path

from moogts.views import (MoogtListView, AcceptMoogtView,
                          MoogtCreateView, MoogtReportApiView, MyMoogtListApiView,
                          FollowingMoogtListApiView, LastOpenedMoogtApiView,
                          MoogtDetailView, FollowMoogtAPIView, GetUsersFollowingMoogtApiView,
                          ShareMoogt, UpdateMoogtPublicityStatusView,
                          EndMoogtView, MoogtSuggestionApiView,
                          MoogtSuggestionActionApiView, MoogtSuggestionListApiView,
                          UploadBannerApiView, HasLiveMoogtsView, UpdateMoogtApiView, UpdateAllSuggestionsApiView,
                          MakeCardRequestApiView, CardRequestActionApiView, MakeEndMoogtRequestApiView,
                          EndMoogtRequestActionApiView, QuitMoogtApiView, GetBundleActivitiesApiView,
                          MakePauseMoogtRequestApiView, PauseMoogtRequestActionApiView, MakeResumeMoogtRequestApiView,
                          ResumeMoogtRequestActionApiView, MakeDeleteMoogtRequestApiView,
                          DeleteMoogtRequestActionApiView, GetMoogtHighlightsApiView, MakeMoogtDonationApiView,
                          ListDonationsApiView)

app_name = 'moogts'

urlpatterns = [
    re_path(r'^all/$', MoogtListView.as_view(), name='list'),
    re_path(r'^accept/(?P<pk>\d+)/$', AcceptMoogtView.as_view(), name='accept'),
    re_path(r'^create/$', MoogtCreateView.as_view(), name='create'),
    re_path(r'^banner/upload/$', UploadBannerApiView.as_view(),
            name='upload_banner'),
    re_path(r'^my/$', MyMoogtListApiView.as_view(), name='my_moogt_list'),
    re_path(r'^followings/$', FollowingMoogtListApiView.as_view(),
            name='following_moogt_list'),
    re_path(r'^last-opened/$', LastOpenedMoogtApiView.as_view(),
            name='last_opened_moogt'),
    re_path(r'^detail/(?P<pk>\d+)/$', MoogtDetailView.as_view(), name='detail'),
    re_path(r'^follow/(?P<pk>\d+)/$',
            FollowMoogtAPIView.as_view(), name='follow_moogt'),
    re_path(r'^following/user/(?P<pk>\d+)/$',
            GetUsersFollowingMoogtApiView.as_view(), name='users_following'),
    re_path(r'^share/(?P<pk>\d+)/$', ShareMoogt.as_view(), name='share_moogt'),
    re_path(r'^update-publicity/$', UpdateMoogtPublicityStatusView.as_view(),
            name='update_moogt_publicity'),
    re_path(r'^update/(?P<pk>\d+)/$',
            UpdateMoogtApiView.as_view(), name='update_moogt'),
    re_path(r'^report/(?P<pk>\d+)/$',
            MoogtReportApiView.as_view(), name='report_moogt'),
    re_path(r'^end/(?P<pk>\d+)/$', EndMoogtView.as_view(), name='end_moogt'),
    re_path(r'^suggestion/create/$', MoogtSuggestionApiView.as_view(),
            name='create_moogt_suggestion'),
    re_path(r'^suggestion/change/$', MoogtSuggestionActionApiView.as_view(),
            name='update_moogt_suggestion'),
    re_path(r'^suggestion/change/all/(?P<pk>\d+)/$',
            UpdateAllSuggestionsApiView.as_view(),
            name='update_all_moogt_suggestion'),
    re_path(r'^suggestion/all/(?P<pk>\d+)/$',
            MoogtSuggestionListApiView.as_view(), name='list_moogt_suggestion'),
    re_path(r'^has-moogts/$', HasLiveMoogtsView.as_view(),
            name='has_live_moogts'),
    re_path(r'^request/card/(?P<pk>\d+)/$',
            MakeCardRequestApiView.as_view(), name='request_card'),
    re_path(r'^request/card/action/(?P<pk>\d+)/$',
            CardRequestActionApiView.as_view(), name='card_request_action'),
    re_path(r'^request/end/(?P<pk>\d+)/$',
            MakeEndMoogtRequestApiView.as_view(), name='request_end_moogt'),
    re_path(r'^request/end/action/(?P<pk>\d+)/$', EndMoogtRequestActionApiView.as_view(),
            name='end_moogt_request_action'),
    re_path(r'^request/pause/(?P<pk>\d+)/$',
            MakePauseMoogtRequestApiView.as_view(), name='request_pause_moogt'),
    re_path(r'^request/pause/action/(?P<pk>\d+)/$', PauseMoogtRequestActionApiView.as_view(),
            name='pause_moogt_request_action'),
    re_path(r'^request/resume/(?P<pk>\d+)/$',
            MakeResumeMoogtRequestApiView.as_view(), name='request_resume_moogt'),
    re_path(r'^request/resume/action/(?P<pk>\d+)/$', ResumeMoogtRequestActionApiView.as_view(),
            name='resume_moogt_request_action'),
    re_path(r'^request/delete/(?P<pk>\d+)/$',
            MakeDeleteMoogtRequestApiView.as_view(), name='request_delete_moogt'),
    re_path(r'^request/delete/action/(?P<pk>\d+)/$', DeleteMoogtRequestActionApiView.as_view(),
            name='delete_moogt_request_action'),
    re_path(r'^highlights/(?P<pk>\d+)/$',
            GetMoogtHighlightsApiView.as_view(), name='get_moogt_highlights'),
    re_path(r'^donate/(?P<pk>\d+)/$',
            MakeMoogtDonationApiView.as_view(), name='make_moogt_donation'),
    re_path(r'^donate/all/(?P<pk>\d+)/$',
            ListDonationsApiView.as_view(), name='list_moogt_donations'),
    re_path(r'^quit/(?P<pk>\d+)/$',
            QuitMoogtApiView.as_view(), name='quit_moogt'),
    re_path(r'^bundle/(?P<pk>\d+)/$',
            GetBundleActivitiesApiView.as_view(), name='bundle_activities')
]
