# Generated by Django 2.2 on 2020-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20200613_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
