# Generated by Django 2.2 on 2020-08-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_is_removed'),
        ('polls', '0003_pollscore_overall_score'),
    ]

    operations = [
    ]
