# Generated by Django 2.2 on 2021-04-03 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_merge_20200803_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
