# Generated by Django 2.2 on 2021-06-17 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_poll_comment_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
