# Generated by Django 2.2 on 2022-03-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20220317_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pollreport',
            name='remark',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
