# Generated by Django 2.1.3 on 2018-11-23 02:40

from django.conf import settings
from django.db import migrations


def update_site_name(apps, schema_editor):
    SiteModel = apps.get_model('sites', 'Site')

    SiteModel.objects.update_or_create(
        pk=settings.SITE_ID,
        domain=settings.SITE_DOMAIN_NAME,
        name=settings.SITE_DOMAIN_NAME
    )


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(update_site_name),
    ]
