# Generated by Django 2.2 on 2020-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('meda', '0002_timestampablemock'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaggableMock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tags', models.ManyToManyField(blank=True, to='api.Tag')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
