# Generated by Django 2.2 on 2020-12-03 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meda', '0003_taggablemock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timestampablemock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
    ]
