# Generated by Django 2.2 on 2020-09-15 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderatorsuggestion',
            name='invitation',
        ),
    ]
