# Generated by Django 2.2 on 2020-10-08 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0002_remove_moderatorsuggestion_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EDITED', 'EDITED')], default='PENDING', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='moderatorsuggestion',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EDITED', 'EDITED')], default='PENDING', max_length=50),
        ),
    ]
