# Generated by Django 2.2 on 2020-10-09 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0003_auto_20201008_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='parent_invitation',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_invitation', to='invitations.Invitation'),
        ),
    ]
