# Generated by Django 2.2 on 2021-12-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0006_auto_20211214_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorinvitation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='moderatorinvitation',
            name='updated_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
