# Generated by Django 2.2 on 2022-03-09 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0007_auto_20211214_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderatorinvitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=50),
        ),
    ]
