# Generated by Django 2.2 on 2022-12-24 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0008_auto_20220309_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EDITED', 'EDITED'), ('REVISED', 'REVISED'), ('STARTED', 'STARTED')], default='PENDING', max_length=50, null=True),
        ),
    ]
