# Generated by Django 4.2.5 on 2023-09-22 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0009_auto_20221224_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled'), ('EDITED', 'EDITED'), ('REVISED', 'REVISED'), ('STARTED', 'STARTED'), ('ACCEPTED_BY_ONE_INVITEE', 'ACCEPTED_BY_ONE_INVITEE')], default='PENDING', max_length=50, null=True),
        ),
    ]
