# Generated by Django 2.2 on 2020-06-10 12:45

import annoying.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('arguments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=560, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'To the public'), ('FOLLOWERS_ONLY', 'To my subscribers only')], default='PUBLIC', max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('banner', models.ImageField(blank=True, upload_to='')),
                ('is_hidden', models.BooleanField(default=False)),
                ('type', models.CharField(choices=[('VIEW', 'View'), ('VIEW_REACTION', 'View reaction view'), ('ARGUMENT_REACTION', 'Argument reaction view')], default='VIEW', max_length=25)),
                ('reaction_type', models.CharField(choices=[('ENDORSE', 'Endorse'), ('DISAGREE', 'Disagree'), ('APPLAUD', 'Applaud')], max_length=25, null=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('parent_argument', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='argument_reactions', to='arguments.Argument')),
                ('parent_view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_reactions', to='views.View')),
                ('tags', models.ManyToManyField(blank=True, related_name='views', to='api.Tag')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ViewScore',
            fields=[
                ('score_now', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('score_before', models.DecimalField(decimal_places=2, default=0, max_digits=11)),
                ('score_last_updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('view', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='score', serialize=False, to='views.View')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ViewImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('view', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='views.View')),
            ],
        ),
        migrations.CreateModel(
            name='ViewStats',
            fields=[
                ('view', annoying.fields.AutoOneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='stats', serialize=False, to='views.View')),
                ('applauds', models.ManyToManyField(related_name='_viewstats_applauds_+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
