# Generated by Django 2.2 on 2020-06-28 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0002_auto_20200613_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='view',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='view',
            name='is_comment_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
