# Generated by Django 2.2 on 2020-07-31 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0003_view_is_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewscore',
            name='overall_score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
        ),
    ]
