# Generated by Django 2.2 on 2020-08-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0004_viewscore_overall_score'),
        ('views', '0004_view_is_removed'),
    ]

    operations = [
    ]
