# Generated by Django 2.2 on 2021-02-08 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0006_view_comment_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='banner',
        ),
    ]
