# Generated by Django 2.2 on 2022-03-14 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0008_viewreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewreport',
            name='view',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='views.View'),
        ),
    ]
