# Generated by Django 2.2 on 2022-03-14 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('views', '0009_auto_20220314_0712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='view',
            name='parent_argument',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='argument_reactions', to='arguments.Argument'),
        ),
        migrations.AlterField(
            model_name='view',
            name='parent_view',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_reactions', to='views.View'),
        ),
        migrations.AlterField(
            model_name='view',
            name='reaction_type',
            field=models.CharField(blank=True, choices=[('ENDORSE', 'Endorse'), ('DISAGREE', 'Disagree'), ('APPLAUD', 'Applaud')], max_length=25, null=True),
        ),
    ]
