# Generated by Django 2.2 on 2020-07-28 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogt',
            name='is_removed',
            field=models.BooleanField(default=False),
        ),
    ]
