# Generated by Django 2.2 on 2020-08-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0002_moogt_is_removed'),
        ('moogts', '0002_moogtscore_overall_score'),
    ]

    operations = [
    ]
