# Generated by Django 2.2 on 2020-09-03 07:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import moogts.enums


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moogts', '0003_merge_20200803_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoogtMiniSuggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('resolution', models.CharField(max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=560, null=True)),
                ('max_duration', models.DurationField(null=True)),
                ('idle_timeout_duration', models.DurationField(null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'To the public'), ('FOLLOWERS_ONLY', 'To my subscribers only')], max_length=15, null=True)),
                ('state', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved')], default=moogts.enums.MiniSuggestionState('Pending'), max_length=15)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moogt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mini_suggestions', to='moogts.Moogt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
