# Generated by Django 2.2 on 2020-10-05 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('moogts', '0005_auto_20200930_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogtminisuggestion',
            name='suggested_child',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_parent', to='moogts.MoogtMiniSuggestion'),
        ),
        migrations.AddField(
            model_name='moogtminisuggestion',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.Tag'),
        ),
    ]
