# Generated by Django 2.2 on 2020-10-15 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0006_auto_20201005_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moogtminisuggestion',
            name='state',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('DISAPPROVED', 'Disapproved'), ('CANCEL', 'cancel'), ('EDITED', 'edited')], default='Pending', max_length=15),
        ),
    ]
