# Generated by Django 2.2 on 2020-10-21 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0007_auto_20201015_0834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moogt',
            name='max_duration',
            field=models.DurationField(null=True),
        ),
    ]
