# Generated by Django 2.2 on 2020-10-28 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0008_auto_20201021_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoogtBanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner', models.ImageField(upload_to='banners')),
            ],
        ),
        migrations.RemoveField(
            model_name='moogt',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='moogt',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moogt', to='moogts.MoogtBanner'),
        ),
    ]
