# Generated by Django 2.2 on 2020-11-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0010_auto_20201113_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogtminisuggestion',
            name='stop_countdown',
            field=models.BooleanField(default=False),
        ),
    ]
