# Generated by Django 2.2 on 2020-12-01 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moogts', '0011_moogtminisuggestion_stop_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoogtActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'PENDING'), ('Accepted', 'ACCEPTED'), ('Declined', 'DECLINED')], default='Pending', max_length=15)),
                ('type', models.CharField(choices=[('CARD_REQUEST', 'CARD_REQUEST')], default=None, max_length=10, null=True)),
                ('moogt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='moogts.Moogt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
