# Generated by Django 2.2 on 2020-12-06 21:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moogts', '0013_auto_20201201_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogt',
            name='is_paused',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='moogt',
            name='paused_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moogt',
            name='paused_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paused_moogt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='moogt',
            name='resumed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='moogt',
            name='resumed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumed_moogt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='moogtactivity',
            name='type',
            field=models.CharField(choices=[('CARD_REQUEST', 'CARD_REQUEST'), ('END_REQUEST', 'END_REQUEST'), ('PAUSE_REQUEST', 'PAUSE_REQUEST'), ('RESUME_REQUEST', 'RESUME_REQUEST')], default=None, max_length=15, null=True),
        ),
    ]
