# Generated by Django 2.2 on 2020-12-08 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0014_auto_20201205_0807'),
        ('moogts', '0014_auto_20201206_2132'),
    ]

    operations = [
    ]
