# Generated by Django 2.2 on 2020-12-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0016_auto_20201209_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moogtactivity',
            name='type',
            field=models.CharField(choices=[('CARD_REQUEST', 'CARD_REQUEST'), ('END_REQUEST', 'END_REQUEST'), ('PAUSE_REQUEST', 'PAUSE_REQUEST'), ('RESUME_REQUEST', 'RESUME_REQUEST'), ('DELETE_REQUEST', 'DELETE_REQUEST')], default=None, max_length=15, null=True),
        ),
    ]
