# Generated by Django 2.2 on 2020-12-11 08:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moogts', '0017_auto_20201211_0753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('donation_for_proposition', models.BooleanField(default=None, null=True)),
                ('message', models.CharField(max_length=200)),
                ('level', models.CharField(choices=[('LEVEL_1', 'Level One'), ('LEVEL_2', 'Level Two'), ('LEVEL_3', 'Level Three'), ('LEVEL_4', 'Level Four'), ('LEVEL_5', 'Level Five')], default='LEVEL_1', max_length=7)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moogt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='moogts.Moogt')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
