# Generated by Django 2.2 on 2020-12-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0018_donation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
