# Generated by Django 2.2 on 2021-01-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0021_donation_donated_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
