# Generated by Django 2.2 on 2021-01-13 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0022_auto_20210102_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogtminisuggestion',
            name='banner',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='moogts.MoogtBanner'),
        ),
        migrations.AddField(
            model_name='moogtminisuggestion',
            name='remove_banner',
            field=models.BooleanField(default=False),
        ),
    ]
