# Generated by Django 2.2 on 2021-04-04 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0026_auto_20210330_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
