# Generated by Django 2.2 on 2021-04-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0027_donation_is_anonymous'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='amount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='message',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
