# Generated by Django 2.2 on 2021-04-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0027_donation_is_anonymous'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogt',
            name='last_posted_by_proposition',
            field=models.BooleanField(default=False),
        ),
    ]
