# Generated by Django 2.2 on 2021-04-17 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0028_auto_20210410_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoogtActivityBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('moogt', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bundles', to='moogts.Moogt')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='moogtactivity',
            name='bundle',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='moogts.MoogtActivityBundle'),
        ),
    ]
