# Generated by Django 2.2 on 2021-04-13 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0028_auto_20210410_1242'),
        ('moogts', '0028_moogt_last_posted_by_proposition'),
    ]

    operations = [
    ]
