# Generated by Django 2.2 on 2021-04-17 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0029_auto_20210417_0747'),
        ('moogts', '0029_merge_20210413_0718'),
    ]

    operations = [
    ]
