# Generated by Django 2.2 on 2021-04-19 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arguments', '0021_auto_20210330_1210'),
        ('moogts', '0030_merge_20210417_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='moogtactivity',
            name='react_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moogter_reaction_activities', to='arguments.Argument'),
        ),
    ]
