# Generated by Django 2.2 on 2022-02-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moogts', '0032_auto_20210426_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moogtactivity',
            name='type',
            field=models.CharField(choices=[('CARD_REQUEST', 'CARD_REQUEST'), ('END_REQUEST', 'END_REQUEST'), ('PAUSE_REQUEST', 'PAUSE_REQUEST'), ('RESUME_REQUEST', 'RESUME_REQUEST'), ('DELETE_REQUEST', 'DELETE_REQUEST'), ('ENDORSEMENT', 'ENDORSEMENT'), ('DISAGREEMENT', 'DISAGREEMENT'), ('QUIT', 'QUIT')], default=None, max_length=15, null=True),
        ),
    ]
