# Generated by Django 2.2 on 2021-04-26 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('normal', 'normal'), ('message', 'message')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('normal', 'normal'), ('regular_message', 'regular_message'), ('invitation_message', 'invitation_message'), ('mini_suggestion_message', 'mini_suggestion_message')], default='normal', max_length=20),
        ),
    ]
