# Generated by Django 2.2 on 2021-05-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0009_auto_20210519_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('moogt_status', 'moogt_status'), ('moogt_request', 'moogt_request'), ('moogt_request_resolved', 'moogt_request_resolved'), ('moogt_card', 'moogt_card'), ('moogt_follow', 'moogt_follow'), ('moogt_premiere', 'moogt_premiere'), ('moogt_conclude', 'moogt_conclude'), ('mini_suggestion_new', 'mini_suggestion_new'), ('mini_suggestion_action', 'mini_suggestion_action'), ('invitation_sent', 'invitation_sent'), ('invitation_start_anytime', 'invitation_start_anytime'), ('invitation_accept_invitee', 'invitation_accept_invitee'), ('invitation_accept_inviter', 'invitation_accept_inviter'), ('regular_message', 'regular_message')], max_length=50, null=True),
        ),
    ]
