# Generated by Django 2.2 on 2021-05-27 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0012_auto_20210522_0928'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='parent_notification',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_notifications', to='notifications.Notification'),
        ),
    ]
