# Generated by Django 2.2 on 2021-06-01 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_notification_parent_notification'),
        ('notifications', '0013_auto_20210529_0836'),
    ]

    operations = [
    ]
