# Generated by Django 2.2 on 2022-03-09 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0016_auto_20220111_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('moogt_status', 'moogt_status'), ('moogt_request', 'moogt_request'), ('moogt_request_resolved', 'moogt_request_resolved'), ('moogt_card', 'moogt_card'), ('moogt_follow', 'moogt_follow'), ('moogt_premiere', 'moogt_premiere'), ('moogt_conclude', 'moogt_conclude'), ('mini_suggestion_new', 'mini_suggestion_new'), ('mini_suggestion_action', 'mini_suggestion_action'), ('invitation_sent', 'invitation_sent'), ('invitation_start_anytime', 'invitation_start_anytime'), ('invitation_accept_invitee', 'invitation_accept_invitee'), ('invitation_accept_inviter', 'invitation_accept_inviter'), ('view_applaud', 'view_applaud'), ('view_comment', 'view_comment'), ('view_agree', 'view_agree'), ('view_disagree', 'view_disagree'), ('argument_applaud', 'argument_applaud'), ('argument_comment', 'argument_comment'), ('argument_agree', 'argument_agree'), ('argument_disagree', 'argument_disagree'), ('argument_request', 'argument_request'), ('argument_request_resolved', 'argument_request_resolved'), ('poll_vote', 'poll_vote'), ('poll_comment', 'poll_comment'), ('poll_closed', 'poll_closed'), ('comment_applaud', 'comment_applaud'), ('comment_reply', 'comment_reply'), ('user_follow', 'user_follow'), ('regular_message', 'regular_message'), ('moderator_request', 'moderator_request'), ('accept_moderator_invitation', 'accept_moderator_invitation'), ('decline_moderator_invitation', 'decline_moderator_invitation')], max_length=50, null=True),
        ),
    ]
